---
  Files: # The files which are plotted together
    - C:/Users/flohu/OneDrive/Documents/Uni/Bachelor/BachelorArbeit/Daten/2020-07-08T11-51-40_HPK_VPX33234_016_PSSnvir_HM_EE_PQC_Flute_1_Polysilicon_Van-der-Pauw_cross.txt
    - C:/Users/flohu/OneDrive/Documents/Uni/Bachelor/BachelorArbeit/Daten/2020-07-08T11-53-14_HPK_VPX33234_016_PSSnvir_HM_EE_PQC_Flute_1_Reverse_Polysilicon_Van-der-Pauw_cross.txt
    - C:/Users/flohu/OneDrive/Documents/Uni/Bachelor/BachelorArbeit/Daten/2020-07-08T11-58-59_HPK_VPX33234_016_PSSnvir_HM_EE_PQC_Flute_1_N+_Van-der-Pauw_cross.txt    
    - C:/Users/flohu/OneDrive/Documents/Uni/Bachelor/BachelorArbeit/Daten/2020-07-08T12-02-08_HPK_VPX33234_016_PSSnvir_HM_EE_PQC_Flute_1_Reverse_N+_Van-der-Pauw_cross.txt
    - C:/Users/flohu/OneDrive/Documents/Uni/Bachelor/BachelorArbeit/Daten/2020-07-08T12-11-22_HPK_VPX33234_016_PSSnvir_HM_EE_PQC_Flute_1_P-stop_Van-der-Pauw_cross.txt
    - C:/Users/flohu/OneDrive/Documents/Uni/Bachelor/BachelorArbeit/Daten/2020-07-08T12-17-31_HPK_VPX33234_016_PSSnvir_HM_EE_PQC_Flute_1_Reverse_P-stop_Van-der-Pauw_cross.txt
  
  Filetype: ASCII # What kind of type is my file, other options are CSV,JSON, customizations

  Output: C:/Users/flohu/OneDrive/Documents/Uni/Bachelor/BachelorArbeit/Plots #Output folder path for my plots
  backend: bokeh # Choose the backend for the plotting Warning: Output may change with different backends.

  Save_as: # save the plots in different data formats, if more than one is specified all of them will be plotted
    - png
  
  plot_name: Plotversuch0

  Analysis:
    - Van_der_Pauw # The analysis Plugin over which the data will be run. These plugins must be located in the foler "analysis_scripts"
    
  Poolsize: 4 # Maximum pool size of simultaneous analysis scripts

  # Optional Parameters
  ASCII_file_specs: # The specifications for the ascii file type measurements files
    header_lines: 11
    measurement_description: 12
    units_line: 12
    data_start: 13

  Van_der_Pauw:
    plateau: 0.03
    #UnitConversion: asd    
    General: # Options common to all plots
          fontsize: {'title': 28, 'labels': 24, 'xticks': 24, 'yticks': 24, 'legend': 11}
          responsive: False
          width: 1200
          height: 800
          shared_axes: False
          legend_position: top_left # funktioniert nur wenn oben mehr als ein filepfad angegeben ist